# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: HARRepoFileManagerAPI CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build with dotnet
      run: dotnet build HARRepo.FileManager.API/HARRepo.FileManager.API.csproj --configuration Release
      
    - name: Run Tests
      run: dotnet test HARRepo.FileManager.Logic.Tests/HARRepo.FileManager.Logic.Tests.csproj --no-restore --no-build

    - name: dotnet publish
      run: dotnet publish HARRepo.FileManager.API/HARRepo.FileManager.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/FileManagerAPI

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HARRepoFileManagerAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f1128cd15a5a47ccacb7a9f8ba15383f }}
        package: ${{env.DOTNET_ROOT}}/FileManagerAPI 
